
name: MarcoFreedomMod v2
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: Plugin originally for the Total Freedom server, modified to fit the needs of MarcoFreedom instead.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials]
authors: [Madgeek1450, Prozza, Mafrans]

# plugin.yml is no longer used to define commands.
